### ISSUE TITLE
Environment setup

### ISSUE THREAD

**Issue by jeewenjie** [dr-costas/clotho-baseline-dataset#1]
Hi, may I know what is the environmental set-up? Python version, dependencies required etc.

**Comment by dr-costas** [comment]
Hey! Sorry for the delayed reply. 

Supported Python version is at least 3.5. I will add the dependencies sortly.

**Comment by dr-costas** [comment]
Hi again, 

I just added a conda requirements file that contains all the necessary packages. 

The actual dependencies are just the packages:

1. numpy
2. librosa
3. pyyaml
4. loguru

and Python version 3.7.

With the `clotho_conda_requirements.yaml` you can see every package installed when installing the above four and using Python v.3.7. 

There are also instructions at the README file, regarding how to create a conda environment just for running the code of this repository and not affecting your current working conda env. 

Since this issue was for the environment setup, I will close it. If you have any new issues, please create a new issue here :)

Enjoy!

**Comment by jeewenjie** [comment]
Thank you!
